language: java

install: mvn -DpentahoInstall=false -DpentahoInstallDir=./target/pdi/plugins/steps/ic-riak-plugin install
script: mvn -DpentahoInstall=false -DpentahoInstallDir=./target/pdi/plugins/steps/ic-riak-plugin test
# coveralls
after_success: mvn clean cobertura:cobertura coveralls:cobertura
